image: $CI_REGISTRY/ricardomartincoski_opensource/utootlkm-uml/utootlkm-uml:20230206.0101

variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  before_script:
    # avoid https://gitlab.com/gitlab-org/gitlab-runner/-/issues/29022
    - git config --global --add safe.directory ${CI_PROJECT_DIR}
    # improve troubleshooting for passing artifacts from one job to another
    - for dir in
        .
        download
        output/build
        output/images
        ; do if [ -d $dir ]; then echo $dir ; ls -la $dir ; fi; done

cache:
  key: single-cache
  paths:
    - download/
  policy: pull-push

linux:
  script:
    - make V=1 linux
  artifacts:
    when: always
    expire_in: 4 hours
    paths:
      - .stamp_*
      - output/build/linux/
      - output/images/

rootfs_initial:
  script:
    - make V=1 rootfs_initial
  artifacts:
    when: always
    expire_in: 4 hours
    paths:
      - .stamp_*
      - output/build/rootfs_initial/.config
      - output/build/rootfs_initial/build/build-time.log
      - output/build/rootfs_initial/build/packages-file-list.txt
      - output/build/rootfs_initial/build/*/.config
      - output/images/

rootfs_partial:
  needs:
    - job: linux
      artifacts: true
    - job: rootfs_initial
      artifacts: true
  script:
    - make V=1 rootfs_partial
  artifacts:
    when: always
    expire_in: 4 hours
    paths:
      - .stamp_*
      - output/build/*/.config
      - output/images/

rootfs_final:
  needs:
    - job: rootfs_partial
      artifacts: true
  script:
    - make V=1 rootfs_final
  artifacts:
    when: always
    expire_in: 4 hours
    paths:
      - .stamp_*
      - output/build/*/.config
      - output/images/

tests:
  needs:
    - job: linux
      artifacts: true
    - job: rootfs_final
      artifacts: true
  script:
    - make V=1 tests
  artifacts:
    when: always
    paths:
      - .stamp_*
      - output/build/*/.config
      - output/images/
      - output/tests/

retest:
  needs:
    - job: tests
      artifacts: true
  script:
    - make V=1 retest
  artifacts:
    when: always
    paths:
      - .stamp_*
      - output/build/*/.config
      - output/images/
      - output/tests/
